name = "temc"
main = "_worker.js"
compatibility_date = "2025-04-02"
assets={directory: "./dist"}
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "d89d2a0e-24c4-4783-a1e8-610788065f89"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
